# Generated by Django 4.2.4 on 2024-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent')], default=3),
            preserve_default=False,
        ),
    ]
